## Service definition ##
application:
  schemaVersion: 1.0.0-preview1
  name: VotingApplication
  properties:
    services:
      - name: VotingData
        properties:
          description: VotingData description.
          osType: Windows
          codePackages:
            - name: VotingData
              image: votingdata:dev
              endpoints:
                - name: VotingDataEndpoint
                  port: 20004
              environmentVariables:
                - name: ASPNETCORE_URLS
                  value: http://+:20004
#                - name: ApplicationInsights:InstrumentationKey
#                  value: "<Place AppInsights key here, or reference it via a secret>"
              resources:
                requests:
                  cpu: 0.5
                  memoryInGB: 1
              reliableCollectionsRefs:
                - name: VotingDataCollections
          replicaCount: 1
          networkRefs:
            - name: VotingApplicationNetwork